### ISSUE TITLE
benchopt generate-results produces html giving a File not found 

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#230]
```
(base) ➜  lasso git:(flash) ✗ pwd
/home/mathurin/workspace/benchmarks/lasso
(base) ➜  lasso git:(flash) ✗ benchopt generate-results -b . 
Rendering benchmark: .
Processing outputs/benchopt_run_2021-11-05_08h30m08.csv
Processing outputs/benchopt_run_2021-11-05_08h30m38.csv
Processing outputs/benchopt_run_2021-11-05_08h34m48.csv
Solver sklearn did not reach precision 1e-06.
Processing outputs/benchopt_run_2021-11-05_08h36m28.csv
Processing outputs/benchopt_run_2021-11-05_09h05m37.csv
Solver sklearn did not reach precision 1e-06.
Solver sklearn did not reach precision 1e-06.
Solver sklearn did not reach precision 1e-06.
Solver sklearn did not reach precision 1e-06.
Solver sklearn did not reach precision 1e-06.
Solver sklearn did not reach precision 1e-06.
Writing  results to html.html
Writing results to html/__benchopt_run_2021-11-05_08h30m08.html
Writing results to html/__benchopt_run_2021-11-05_08h30m38.html
Writing results to html/__benchopt_run_2021-11-05_08h34m48.html
Writing results to html/__benchopt_run_2021-11-05_08h36m28.html
Writing results to html/__benchopt_run_2021-11-05_09h05m37.html
Writing index to html/index.html
```

This opens a valid html:
![image](https://user-images.githubusercontent.com/8993218/140491341-60965522-c7ba-4c7b-a376-b135baa99268.png)
but if I try to click on the benchmarks rectangle, I get:
![image](https://user-images.githubusercontent.com/8993218/140491384-f95e48bd-f0db-4708-a684-50ae8e39e368.png)

**Comment by mathurinm** [comment]
It turns out this has to be done from the parent directory. This works
```
(base) ➜  benchmarks pwd
/home/mathurin/workspace/benchmarks
(base) ➜  benchmarks benchopt generate-results -b lasso
```

But doing it inside the benchmark folder 
```
(base) ➜  lasso git:(flash) ✗ pwd
/home/mathurin/workspace/benchmarks/lasso
(base) ➜  lasso git:(flash) ✗ benchopt generate-results -b .    
```
produces a malfunctioning html.

I would argue it's more logical to run it from the `benchmark_*` than from the parent folder, but I don't know how you use it.

**Comment by tomMoral** [comment]
The command you are looking for is `benchopt plot --all .` I  think.

The goal of `generate-results` is to create a dashboard for the website. That being said, we should still fix this behavior. I guess this should be solved at the `Benchmark` object level to make sure we always get a name for the HTML file.

**Comment by mathurinm** [comment]
No I really was trying to regenerate the website, because I had deleted html and csv results yet they were still showing on the main page. I think #231  fixes the issue

**Comment by tomMoral** [comment]
Ok but don't `benchopt plot --all .` generate the lasso webpage?
